# Generated by Django 4.2.13 on 2024-07-05 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_student_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('char', 'CharField'), ('int', 'IntegerField'), ('choice', 'ChoiceField')], max_length=10)),
                ('choices', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 5), null=True),
        ),
        migrations.AlterField(
            model_name='receiption',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='receiptionadmin',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='26335672', max_length=150, unique=True),
        ),
    ]
