# Generated by Django 4.2.13 on 2024-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_attendance_date_alter_attendancegroup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='75801413', max_length=150, unique=True),
        ),
    ]
