# Generated by Django 4.2.13 on 2024-07-15 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='time',
            field=models.CharField(choices=[('7.30:9.30', '7.30:9.30'), ('2', '10.00:12:00'), ('3', '13.00:15.00'), ('4', '15.30:17.30')], max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 15), null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='receiption',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
        migrations.AlterField(
            model_name='receiptionadmin',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='85832136', max_length=150, unique=True),
        ),
    ]
