# Generated by Django 4.2.13 on 2024-07-16 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_alter_attendance_date_alter_attendancegroup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 16)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 16)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='time',
            field=models.CharField(choices=[('1', '7.30:9.30'), ('2', '10.00:12:00'), ('3', '13.00:15.00'), ('4', '15.30:17.30')], max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 16), null=True),
        ),
        migrations.AlterField(
            model_name='receiption',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 16)),
        ),
        migrations.AlterField(
            model_name='receiptionadmin',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 16)),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='50452239', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
