# Generated by Django 4.2.13 on 2024-07-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_attendance_date_alter_attendancegroup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiption',
            name='info_text',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 17), null=True),
        ),
        migrations.AlterField(
            model_name='receiption',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
        ),
        migrations.AlterField(
            model_name='receiptionadmin',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='54009541', max_length=150, unique=True),
        ),
    ]
