# Generated by Django 4.2.13 on 2024-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_student_token_id_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='51320155', max_length=150, unique=True),
        ),
    ]
