# Generated by Django 4.2.13 on 2024-07-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.studentcourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='95497478', max_length=150, unique=True),
        ),
    ]
