# Generated by Django 4.2.13 on 2024-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_attendancegroup_course_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='64256414', max_length=150, unique=True),
        ),
    ]
