# Generated by Django 4.2.7 on 2024-07-18 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='attendancegroup',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 18), null=True),
        ),
        migrations.AlterField(
            model_name='receiption',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='receiptionadmin',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 18)),
        ),
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='14431915', max_length=150, unique=True),
        ),
    ]
