# Generated by Django 4.2.7 on 2024-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_attendance_date_alter_attendancegroup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='51749747', max_length=150, unique=True),
        ),
    ]
