# Generated by Django 4.2.7 on 2024-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='47347100', max_length=150, unique=True),
        ),
    ]
