# Generated by Django 4.2.7 on 2024-07-18 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_givesalary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givesalary',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 18), null=True),
        ),
    ]
